name: .NET
env: 
  SDK_VERSION: 1.1.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  compile:
    strategy:
      max-parallel: 2
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  calc-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    needs:
      - compile
    outputs:
      version: ${{ steps.v.outputs.version }}
    steps:
      - id: v
        run: |
          if [ "${{ github.ref }}" = 'refs/heads/master' ]; then
            echo "version=${SDK_VERSION}" >> $GITHUB_OUTPUT
          else
            echo "version=${SDK_VERSION}-develop.${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi

  publish:
    name: Build and Publish NuGets
    runs-on: windows-latest
    needs:
      - calc-version    

    steps:
    - name: Version Output Check
      run: |
        echo "${{ needs.calc-version.outputs.version }}"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Publish Nuget
      uses: drusellers/publish-nuget@master
      with:
        project-file-path: GreatIdeas.MailServices.MsGraph/GreatIdeas.MailServices.MsGraph.csproj
        version: ${{ needs.calc-version.outputs.version }}
        tag-commit: false
        nuget-key: ${{secrets.NUGET_API_KEY}}

